[tools]
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "x" }
stylua = { source = "JohnnyMorganz/stylua", version = "x" }
selene = { source = "kampfkarren/selene", version = "x" }
wally = { source = "UpliftGames/wally", version = "x" }
rojo = { source = "rojo-rbx/rojo", version = "x" }