name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install required tools
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release to Wally
        shell: bash
        env:
          WALLY_AUTH: ${{ secrets.WALLY_AUTH }}
        run: |
          mkdir -p ~/.wally
          echo "$WALLY_AUTH" > ~/.wally/auth.toml
          wally publish

      - name: Install WrapperService
        shell: bash
        run: |
          cd publish
          wally install
          cd ..

      - name: Build place file
        run: |
          cd publish
          rojo build publish.project.json -o WrapperService.rbxl
          cd ..

      - name: Create .rbxm file
        shell: bash
        run: |
          cd publish
          remodel run build.lua
          cd ..

      - name: Create .zip file
        shell: bash
        run: |
          cd publish
          zip -r WrapperService.zip Packages
          cd ..

      - name: Create release note
        shell: bash
        run: |
          sed -i -e '1,6d' CHANGELOG.md
          python3 publish/get_changes.py CHANGELOG.md > publish/CHANGES.md
          cd publish
          sed -i 's|(rbxm)|(https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/WrapperService.rbxm)|' RELEASE_NOTE.md
          sed -i 's|(zip)|(https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/WrapperService.zip)|' RELEASE_NOTE.md
          sed -i 's|version|${{ github.ref_name }}|' RELEASE_NOTE.md
          cat CHANGES.md >> RELEASE_NOTE.md
          cd ..
      
      - name: Publish release to github
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ github.ref_name }}
          fail_on_unmatched_files: true
          body_path: publish/RELEASE_NOTE.md
          files: |
              publish/WrapperService.rbxm
              publish/WrapperService.zip
